#!/usr/bin/env python3
"""Render system/blockMeshDict for a grid level — PRODUCTION DUCT (D-10).

Tight channel duct (D-10 rev): 46 mm (y) x 72 mm (z) = module + 4 mm side /
7 mm top clearance; flow along x in [-90,90]. Gap Re = 36/65/94 at D-11 flows.
Patches: inlet (x-), outlet (x+), walls (adiabatic, §4.3).

Levels scale the background cell count by r = 1.3 per direction from the
coarse base (60 x 40 x 50 = 2 mm cells in the Liu box); snappy refinement
levels are unchanged, so near-cell resolution scales with the background.

    coarse: 90 x 40 x 50 background (duct)
    medium/fine: scaled by R per direction (see R below)

Usage: makeMesh.py [coarse|medium|fine]   (default coarse)
"""

import sys
from pathlib import Path

CASE = Path(__file__).resolve().parent
R = 1.35   # background scale; achieved volumetric r was ~1.26 at 1.3
           # (snappy surface refinement lags the background), 1.35 clears
           # Celik's r > 1.3 with margin. Verified counts (at 1.3): coarse
           # 218k / medium 441k / fine 874k, all regions Mesh OK, skew <= 2.5.
BASE = (90, 23, 36)   # 2 mm cells: 180 x 46 x 72 mm TIGHT duct (D-10 rev)
GRIDS = {
    "coarse": 1.0,
    "medium": R,
    "fine": R * R,
}

grid = sys.argv[1] if len(sys.argv) > 1 else "coarse"
if grid not in GRIDS:
    sys.exit(f"unknown grid '{grid}' (coarse|medium|fine)")
s = GRIDS[grid]
nx, ny, nz = (round(n * s) for n in BASE)

(CASE / "system/blockMeshDict").write_text(f"""FoamFile
{{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      blockMeshDict;
}}
// Generated by makeMesh.py — do not edit. Grid level: {grid}
// (r = 1.3 per direction from the 2 mm coarse base; §4.8 GCI family).
// Background block = inner cavity of Liu et al.'s acrylic box (D-09 rig),
// 120 x 80 x 100 mm; module placement TODO(validation) pending figures.

scale   0.001;

vertices
(
    (-90 -23   0)
    ( 90 -23   0)
    ( 90  23   0)
    (-90  23   0)
    (-90 -23  72)
    ( 90 -23  72)
    ( 90  23  72)
    (-90  23  72)
);

blocks
(
    hex (0 1 2 3 4 5 6 7) ({nx} {ny} {nz}) simpleGrading (1 1 1)
);

boundary
(
    inlet
    {{
        type patch;
        faces ((0 4 7 3));
    }}
    outlet
    {{
        type patch;
        faces ((1 2 6 5));
    }}
    walls               // floor, lid, sides: adiabatic duct (§4.3, D-10)
    {{
        type wall;
        faces
        (
            (0 3 2 1)
            (4 5 6 7)
            (0 1 5 4)
            (3 7 6 2)
        );
    }}
);
""")
print(f"blockMeshDict rendered: grid={grid} ({nx} {ny} {nz})")
