#!/usr/bin/env python3
"""Render all property-dependent dictionaries for the Liu static validation
case from data/reference/properties.yaml + geometry/stl/MANIFEST.sha256.

Generated (never hand-edit):
  constant/fluid/thermophysicalProperties
  constant/cell{0..5}/thermophysicalProperties   (cylindrical CS per cell)
  constant/cell{0..5}/fvOptions                  (volumetric heat source)
  system/cell{0..5}/{changeDictionaryDict,fvSchemes,fvSolution}
  system/monitors                                (#included by controlDict)

PLACEHOLDERS pending Week-3 full-text digitisation (do not trust results):
  - HEAT_W_PER_CELL: constant 3 W/cell smoke value, not Liu's q(C-rate, DoD)
  - BETA: Novec-7200 expansion 1.6e-3 1/K typical HFE value, not verified
"""

import math
import os
import re
from pathlib import Path
import yaml

CASE = Path(__file__).resolve().parent
REPO = next(q for q in CASE.parents
            if (q / "data/reference/properties.yaml").exists())
props = yaml.safe_load((REPO / "data/reference/properties.yaml").read_text())
cell, cool, rig = props["cell"], props["coolant"], props["validation_rig"]
heatgen = yaml.safe_load((REPO / "data/reference/heatgen.yaml").read_text())["liu3c"]

BETA = float(os.environ.get("BETA", 1.6e-3))
                               # PLACEHOLDER 1/K — verify against rho(T) data;
                               # BETA env override for sensitivity diagnostics
if "BETA" in os.environ:
    print(f"** BETA override: {BETA} 1/K (sensitivity run)")
T_BATH = rig["bath_temperature"]

# Inlet waveform (production duct, §3.5/§4.4) from env — generate_cases.py
# sets these per matrix case; defaults give the steady mid-flow baseline.
WAVEFORM = os.environ.get("WAVEFORM", "steady")      # steady|sine|square
QBAR = float(os.environ.get("QBAR_ML_MIN", "90")) / 6e7   # mL/min -> m3/s
FREQ = float(os.environ.get("FREQ_HZ", "1.0"))
AMP = float(os.environ.get("AMP", "0.4"))            # amplitude ratio A
DUTY = float(os.environ.get("DUTY", "0.5"))          # square-wave duty D
T_INLET = 298.15                                     # 25 C coolant supply

# D-07 sensitivity switch: COOLANT_K=0.6 renders the Liu "effective
# conductivity" variant; unset -> the 0.068 physical baseline from the YAML.
_k_env = os.environ.get("COOLANT_K")
if _k_env:
    cool = dict(cool, thermal_conductivity=float(_k_env))
    print(f"** COOLANT_K override: k = {cool['thermal_conductivity']} W/m.K "
          "(D-07 sensitivity run)")

# cell centres from the geometry manifest parameter line
_manifest = CASE / "constant/triSurface/MANIFEST.sha256"
if not _manifest.exists():
    _manifest = REPO / "geometry/stl/MANIFEST.sha256"
params = dict(
    kv.split("=") for kv in
    _manifest.read_text().splitlines()[0].lstrip("# ").split()
)
rows, cols = int(params["rows"]), int(params["cols"])
gap, dia, h, z0 = (float(params[k]) for k in ("gap", "d", "h", "z0"))
pitch = dia + gap
centres = [(-(cols - 1) * pitch / 2 + c * pitch,
            -(rows - 1) * pitch / 2 + r * pitch)
           for r in range(rows) for c in range(cols)]
v_cell = math.pi * (dia / 2) ** 2 * h
# Liu 3C polynomial [W/cell] -> volumetric [W/m3]: Function1 (coeff exp) pairs
poly_pairs = " ".join(f"({a / v_cell:.8g} {n})"
                      for n, a in enumerate(heatgen["coefficients"]))

HEADER = """FoamFile
{{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      {obj};
}}
// Generated by makePhysics.py — do not edit; sources: properties.yaml.

"""


def write(rel, obj, body):
    p = CASE / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(HEADER.format(obj=obj) + body)
    print(f"  wrote {rel}")


# ---- fluid thermo: all-polynomial combo (the only liquid combo available
# ---- to chtMultiRegionFoam's rhoReactionThermo — known trap) -----------
rho25, mu, cp, kappa = (cool["density"], cool["dynamic_viscosity"],
                        cool["specific_heat"], cool["thermal_conductivity"])
a1 = -rho25 * BETA                      # linear rho(T) about 25 C
a0 = rho25 - a1 * 298.15
write("constant/fluid/thermophysicalProperties", "thermophysicalProperties", f"""
thermoType
{{
    type            heRhoThermo;
    mixture         pureMixture;
    transport       polynomial;
    thermo          hPolynomial;
    equationOfState icoPolynomial;
    specie          specie;
    energy          sensibleEnthalpy;
}}

// Novec-7200 (HFE-7200). Constant-property polynomials anchored at 25 C
// except rho(T): linear with PLACEHOLDER beta = {BETA} 1/K (buoyancy driver).
// k = {kappa} W/m.K is the D-07 baseline (0.6 = sensitivity case).
mixture
{{
    specie
    {{
        molWeight   264;        // C4F9OC2H5
    }}
    thermodynamics
    {{
        Hf          0;
        Sf          0;
        CpCoeffs<8> ({cp} 0 0 0 0 0 0 0);
    }}
    transport
    {{
        muCoeffs<8>     ({mu} 0 0 0 0 0 0 0);
        kappaCoeffs<8>  ({kappa} 0 0 0 0 0 0 0);
    }}
    equationOfState
    {{
        rhoCoeffs<8>    ({a0:.6g} {a1:.6g} 0 0 0 0 0 0);
    }}
}}
""")

# ---- per-cell solid thermo + heat source + region dicts --------------------
for i, (cx, cy) in enumerate(centres):
    write(f"constant/cell{i}/thermophysicalProperties", "thermophysicalProperties", f"""
thermoType
{{
    type            heSolidThermo;
    mixture         pureMixture;
    transport       constAnIso;
    thermo          hConst;
    equationOfState rhoConst;
    specie          specie;
    energy          sensibleEnthalpy;
}}

// 18650 jellyroll, anisotropy 29x; local (r, theta, z) via cylindrical CS
// on THIS cell's axis. Interface BCs must use kappaMethod
// directionalSolidThermo + alphaAni aniAlpha (scalar kappa() is mag-collapsed).
coordinateSystem
{{
    type    cylindrical;
    origin  ({cx:.4f} {cy:.4f} {z0});
    rotation
    {{
        type    axes;
        e3      (0 0 1);
        e1      (1 0 0);
    }}
}}

mixture
{{
    specie
    {{
        molWeight   100;
    }}
    thermodynamics
    {{
        Hf          0;
        Sf          0;
        Cp          {cell["specific_heat"]};
    }}
    transport
    {{
        kappa       ({cell["conductivity_radial"]} {cell["conductivity_radial"]} {cell["conductivity_axial"]});
    }}
    equationOfState
    {{
        rho         {cell["density"]};
    }}
}}
""")

    write(f"constant/cell{i}/fvOptions", "fvOptions", f"""
// source-model: liu3c  (marker read by extract_metrics.py)
cellHeat
{{
    type            scalarSemiImplicitSource;
    selectionMode   all;
    volumeMode      specific;       // W/m3
    // Liu et al. 3C heat-generation polynomial (heatgen.yaml, Eq. 5 of the
    // AM), divided by the cell volume {v_cell:.6e} m3. Valid for
    // t in [0, {heatgen["t_discharge"]}] s — the fit DIVERGES past the end
    // of discharge, so endTime must not exceed t_discharge.
    sources
    {{
        h
        {{
            explicit    polynomial ({poly_pairs});
            implicit    none;
        }}
    }}
}}
""")

    write(f"system/cell{i}/changeDictionaryDict", "changeDictionaryDict", f"""
T
{{
    boundaryField
    {{
        // trap: among regex entries the LAST match wins — catch-all first
        ".*"
        {{
            type            zeroGradient;
            value           uniform {T_BATH};
        }}
        // bottom cap on the duct floor: adiabatic (D-10 — duct walls
        // adiabatic per §4.3; no bath behind the production duct)
        walls
        {{
            type            zeroGradient;
        }}
        "cell{i}_to_.*"
        {{
            type            compressible::turbulentTemperatureCoupledBaffleMixed;
            Tnbr            T;
            kappaMethod     directionalSolidThermo;
            alphaAni        aniAlpha;
            value           uniform {T_BATH};
        }}
    }}
}}
""")

    write(f"system/cell{i}/fvSchemes", "fvSchemes", """
ddtSchemes      { default backward; }
gradSchemes     { default Gauss linear; }
divSchemes      { default none; }
laplacianSchemes { default Gauss linear limited corrected 0.5; }
interpolationSchemes { default linear; }
snGradSchemes   { default limited corrected 0.5; }
""")

    write(f"system/cell{i}/fvSolution", "fvSolution", """
// Solid energy matrix is symmetric despite anisotropic kappa -> PCG/DIC
// (DILU aborts; known trap).
solvers
{
    h
    {
        solver          PCG;
        preconditioner  DIC;
        tolerance       1e-8;
        relTol          0.1;
    }
    hFinal
    {
        $h;
        relTol          0;
    }
}

PIMPLE
{
    nNonOrthogonalCorrectors 0;
}
""")

# ---- fluid boundary conditions (duct, §4.3) --------------------------------
# §4.4: EVERY waveform is wrapped in a linearRamp (impulsive inlet start
# spiked Courant to 1.65 in the smoke). Steady ramps over 2 s; pulsed over
# one full period (and metric averaging discards the first periods anyway).
if WAVEFORM == "steady":
    ramp_s, inner = 2.0, f"{{ type constant; value {QBAR:.8g}; }}"
elif WAVEFORM == "sine":
    ramp_s = max(2.0, 1.0 / FREQ)
    inner = f"""{{
                    type        sine;
                    frequency   {FREQ};
                    amplitude   1;
                    scale       {AMP * QBAR:.8g};   // A * Qbar
                    level       {QBAR:.8g};         // Qbar
                    t0          0;
                }}"""
elif WAVEFORM == "square":
    # ON value Qbar/D for fraction D of the period, OFF 0 (§3.5):
    # v2606 Square = a*square(f(t-t0))*s + l with square in [-1,1] and the
    # positive fraction mark/(mark+space). Verified against $FOAM_SRC
    # Square.H/Square.C 2026-09-01 (rule 1): the keys are `mark` and
    # `space` (defaults 1); `markSpace` survives only as a deprecated
    # compat alias for `mark` (v2006) — use the explicit pair.
    ramp_s = max(2.0, 1.0 / FREQ)
    inner = f"""{{
                    type        square;
                    frequency   {FREQ};
                    amplitude   {QBAR / (2 * DUTY):.8g};
                    scale       1;
                    level       {QBAR / (2 * DUTY):.8g};
                    t0          0;
                    mark        {DUTY:.8g};        // ON fraction D
                    space       {1 - DUTY:.8g};    // OFF fraction 1-D
                }}"""
else:
    raise SystemExit(f"unknown WAVEFORM {WAVEFORM}")
flow_entry = f"""volumetricFlowRate
            {{
                type    scale;
                scale   {{ type linearRamp; start 0; duration {ramp_s}; }}
                value   {inner}
            }}"""
print(f"** inlet: {WAVEFORM}, Qbar={QBAR*6e7:.0f} mL/min"
      + (f", f={FREQ} Hz, A={AMP}" if WAVEFORM == "sine" else "")
      + (f", f={FREQ} Hz, D={DUTY}" if WAVEFORM == "square" else ""))

write("system/fluid/changeDictionaryDict", "changeDictionaryDict", f"""
// trap: among regex boundaryField entries the LAST match wins — ".*" first.
U
{{
    boundaryField
    {{
        ".*"    {{ type noSlip; }}
        inlet
        {{
            type            flowRateInletVelocity;
            {flow_entry}
            value           uniform (0 0 0);
        }}
        outlet
        {{
            type            pressureInletOutletVelocity;
            value           uniform (0 0 0);
        }}
    }}
}}

T
{{
    boundaryField
    {{
        ".*"    {{ type zeroGradient; }}     // duct walls adiabatic (D-10)
        inlet   {{ type fixedValue; value uniform {T_INLET}; }}
        outlet  {{ type inletOutlet; inletValue uniform {T_INLET}; value uniform {T_INLET}; }}
        "fluid_to_.*"
        {{
            type            compressible::turbulentTemperatureCoupledBaffleMixed;
            Tnbr            T;
            kappaMethod     fluidThermo;
            value           uniform {T_INLET};
        }}
    }}
}}

p_rgh
{{
    boundaryField
    {{
        ".*"    {{ type fixedFluxPressure; value uniform 101325; }}
        outlet  {{ type fixedValue; value uniform 101325; }}
    }}
}}

p
{{
    boundaryField
    {{
        ".*"    {{ type calculated; value uniform 101325; }}
    }}
}}
""")

# ---- monitors: per-region T extremes + volume averages (metric CSVs) -------
mon = ""
for i in range(len(centres)):
    for op in ("max", "min", "volAverage"):
        mon += f"""
T{op}_cell{i}
{{
    type            volFieldValue;
    libs            (fieldFunctionObjects);
    region          cell{i};
    operation       {op};
    fields          (T);
    regionType      all;
    writeFields     false;
    writeControl    timeStep;
    writeInterval   10;
}}
"""
mon += """
TfluidMinMax
{
    type            fieldMinMax;
    libs            (fieldFunctionObjects);
    region          fluid;
    fields          (T U);
    writeControl    timeStep;
    writeInterval   10;
}

// Liu Fig 9 validation metric: T2 = mid-height SURFACE temperature of a
// middle cell (their thermocouple). Four azimuthal near-surface points in
// cell1 (centre 0,-0.010), r = 8.8 mm, z = 32.5 mm; average in post.
T2probe
{
    type            probes;
    libs            (sampling);
    region          cell1;
    fields          (T);
    probeLocations
    (
        ( 0.0088 -0.0100 0.0325)
        (-0.0088 -0.0100 0.0325)
        ( 0.0000 -0.0012 0.0325)
        ( 0.0000 -0.0188 0.0325)
    );
    writeControl    timeStep;
    writeInterval   10;
}

// live solver-native rho*h storage series: E1's early-window conservation
// gate needs fine cadence (boundary export starts within seconds in a
// tight duct; 30 s saved-field replays are too coarse)
rhoh_fluid
{
    type            volFieldValue;
    libs            (fieldFunctionObjects);
    region          fluid;
    regionType      all;
    operation       weightedVolIntegrate;
    weightField     rho;
    fields          (h);
    writeFields     false;
    writeControl    timeStep;
    writeInterval   10;
}
"""
for i in range(len(centres)):
    mon += f"""
rhoh_cell{i}
{{
    type            volFieldValue;
    libs            (fieldFunctionObjects);
    region          cell{i};
    regionType      all;
    operation       volIntegrate;
    fields          (h);
    writeFields     false;
    writeControl    timeStep;
    writeInterval   10;
}}
"""
mon += """
// stored-energy bookkeeping for the §9 energy balance (extract_metrics.py)
TvolAverage_fluid
{
    type            volFieldValue;
    libs            (fieldFunctionObjects);
    region          fluid;
    operation       volAverage;
    fields          (T);
    regionType      all;
    writeFields     false;
    writeControl    timeStep;
    writeInterval   10;
}

// wall loss on the FLUID side only — solid-side wallHeatFlux is mag(kappa)-
// collapsed and must never be used (docs/environment.md trap).
// Two-stage chain: the FO computes the field EVERY step (cheap, in memory)
// but only writes the volume field at writeTime (trap); the
// surfaceFieldValue below samples the registered field every 10 steps so
// the §9 wall-loss integral resolves the early t^-1/2 transient.
wallLoss_fluid
{
    type            wallHeatFlux;
    libs            (fieldFunctionObjects);
    region          fluid;
    patches         (walls);
    executeControl  timeStep;
    executeInterval 1;
    writeControl    writeTime;   // volume-field trap: tie to writeTime
}

wallLossInt_fluid
{
    type            surfaceFieldValue;
    libs            (fieldFunctionObjects);
    region          fluid;
    regionType      patch;
    name            walls;
    operation       areaIntegrate;
    fields          (wallHeatFlux);
    writeFields     false;
    writeControl    timeStep;
    writeInterval   10;
}
"""
for patch in ("inlet", "outlet"):
    # weightedSum(T) with weightField phi = SIGNED sum(phi*T) — the E1
    # enthalpy-flux integrand. weightedAverage fails on bidirectional faces;
    # areaAverage(T) variant under-reads the buoyant outflow layer ~25x
    # (E1 failed at 75% on the first duct baselines until this was fixed)
    for op, fields in (("sum", "(phi)"), ("areaAverage", "(p T)"),
                       ("weightedSum", "(T)")):
        name = f"TphiSum_{patch}" if op == "weightedSum" else f"{op}_{patch}"
        mon += f"""
{name}
{{
    type            surfaceFieldValue;
    libs            (fieldFunctionObjects);
    region          fluid;
    regionType      patch;
    name            {patch};
    operation       {op};{chr(10) + "    weightField     phi;" if op == "weightedSum" else ""}
    fields          {fields};
    writeFields     false;
    writeControl    timeStep;
    writeInterval   5;
}}
"""
write("system/monitors", "monitors", mon)

# machine-readable case metadata for extract_metrics (E1/E3/E4 gates)
(CASE / "system/caseMeta.yaml").write_text(f"""# generated by makePhysics.py
case_type: duct
waveform: {WAVEFORM}
qbar_m3s: {QBAR:.10g}
freq_hz: {FREQ}
amp: {AMP}
duty: {DUTY}
T_inlet: {T_INLET}
coolant_k: {cool['thermal_conductivity']}
""")
print("  wrote system/caseMeta.yaml")
print("done.")
